{% set name = "gitlab-runner-api" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gitlab_runner_api-{{ version }}.tar.gz
  sha256: e4f82b4cde11c98908e3c88f89f1e7a2527c283ff49a1ec2b1b833c5fbf4b757

build:
  number: 1
  noarch: python
  entry_points:
    - register-runner=gitlab_runner_api:cli.register_runner
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - colorlog
    - python >={{ python_min }}
    - requests
    - setuptools
    - six

test:
  imports:
    - gitlab_runner_api
    - gitlab_runner_api.testing
  commands:
    - pip check
    - register-runner --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chrisburr/gitlab-runner-api/
  license: MIT
  license_file: LICENSE.txt
  summary: "Unofficial implementation of the GitLab runner client for making customised CI runners"
  dev_url: https://github.com/chrisburr/gitlab-runner-api
  doc_url: https://gitlab-runner-api.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisburr
